#!/usr/bin/env bash
# PRODUCTIZATION-4D — build the application bundle for the local appliance.
#
# Same source, same transactional engines, same Nitro fetch-handler artefact as
# the hosted deployment. The ONLY difference is configuration: the client is
# built against a sentinel origin which `stamp-ui.sh` rewrites to the real
# appliance origin at install time, so no customer address is ever baked in.
#
# PRODUCTIZATION-4F: the build must NOT inherit the developer's hosted
# configuration. A checked-in `.env` at the repository root (hosted project
# URL/keys) would otherwise be inlined into the appliance bundle, so we shadow
# it with a temporary `.env.local` (higher precedence, git-ignored) for the
# duration of the build and always restore the previous state.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# The client resolves its API base from its own origin in local mode; this
# value is only the compile-time default for non-browser paths.
SENTINEL="${NOVA_ORIGIN_SENTINEL:-https://localhost:8443}"
ANON="${NOVA_LOCAL_ANON_KEY:-nova-local-anon}"

export VITE_NOVA_RUNTIME_MODE=local
export NOVA_RUNTIME_MODE=local
export VITE_SUPABASE_URL="$SENTINEL"
export VITE_SUPABASE_PUBLISHABLE_KEY="$ANON"
export VITE_SUPABASE_PROJECT_ID=nova-local
export SUPABASE_URL="$SENTINEL"
export SUPABASE_PUBLISHABLE_KEY="$ANON"
export SUPABASE_PROJECT_ID=nova-local

OVERRIDE="$NOVA_ROOT/.env.local"
BACKUP="$NOVA_ROOT/.env.local.nova-backup"
restore_env() {
  if [[ -f "$BACKUP" ]]; then mv -f "$BACKUP" "$OVERRIDE"; else rm -f "$OVERRIDE"; fi
}
[[ -f "$OVERRIDE" ]] && mv -f "$OVERRIDE" "$BACKUP"
trap restore_env EXIT
cat > "$OVERRIDE" <<ENVFILE
# Generated by local/scripts/build-ui.sh — removed automatically after the build.
VITE_SUPABASE_URL=$SENTINEL
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON
VITE_SUPABASE_PROJECT_ID=nova-local
SUPABASE_URL=$SENTINEL
SUPABASE_PUBLISHABLE_KEY=$ANON
SUPABASE_PROJECT_ID=nova-local
VITE_NOVA_RUNTIME_MODE=local
ENVFILE

nova_log "Building NOVA Hospitality UI for the local appliance"
( cd "$NOVA_ROOT" && bun run build )

# The build emits either `.output/{public|client,server}` or, with the current
# Vite config, the appliance layout directly in `dist/`. Normalise whichever
# layout was produced into the appliance contract (`dist/client` +
# `dist/server/index.mjs`) rather than changing the consumer contract.
bash "$NOVA_LOCAL_DIR/scripts/package-bundle.sh" "$NOVA_ROOT"

printf '{"built_at":"%s","origin_sentinel":"%s","runtime_mode":"local"}\n' \
  "$(date -u +%FT%TZ)" "$SENTINEL" > "$NOVA_ROOT/dist/.nova-local-build"
nova_log "UI bundle written to $NOVA_ROOT/dist (local build marker written)"
bash "$NOVA_LOCAL_DIR/scripts/verify-bundle.sh" "$NOVA_ROOT/dist"
