/**
 * Support diagnostics (PRODUCTIZATION-4, Phases N and O).
 *
 * A diagnostic bundle leaves the customer's premises, so redaction is the
 * product feature here — not the formatting. Anything that looks like a
 * secret is replaced before it reaches the bundle.
 */
import { APP_VERSION, NOVA_PRODUCT, REQUIRED_SCHEMA_VERSION } from "../version";

/** Keys whose value is never included, whatever the value looks like. */
export const SENSITIVE_KEY_PATTERN =
  /(password|passwd|secret|token|private[_-]?key|credential|apikey|api[_-]?key|authorization|dsn|connection[_-]?string|jwt)/i;

const SECRET_VALUE_PATTERNS: RegExp[] = [
  /postgres(?:ql)?:\/\/[^\s"']+/gi, // connection strings with credentials
  /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g,
  /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g, // JWTs
  /\bsb_(?:secret|publishable)_[A-Za-z0-9_-]+/g,
];

export const REDACTED = "[redacted]";

export function redactText(input: string): string {
  let out = input;
  for (const pattern of SECRET_VALUE_PATTERNS) out = out.replace(pattern, REDACTED);
  // KEY=value / "key": "value" style assignments for sensitive names.
  out = out.replace(
    /(^|\s|")([A-Za-z0-9_.-]*(?:password|secret|token|private_key|credential|apikey|api_key|jwt)[A-Za-z0-9_.-]*)("?\s*[:=]\s*)("?)([^\s",}]+)/gi,
    (_m, lead, key, sep, quote) => `${lead}${key}${sep}${quote}${REDACTED}`,
  );
  return out;
}

export function redactValue(value: unknown): unknown {
  if (typeof value === "string") return redactText(value);
  if (Array.isArray(value)) return value.map(redactValue);
  if (value && typeof value === "object") return redactRecord(value as Record<string, unknown>);
  return value;
}

export function redactRecord(record: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    out[key] = SENSITIVE_KEY_PATTERN.test(key) ? REDACTED : redactValue(value);
  }
  return out;
}

export interface SystemInformation {
  product: string;
  appVersion: string;
  requiredSchemaVersion: string;
  schemaVersion: string | null;
  runtime: "hosted" | "local";
  installId: string | null;
  postgresVersion: string | null;
  migrationsApplied: number | null;
  lastBackupAt: string | null;
  lastBackupStatus: "verified" | "unverified" | "failed" | "none";
  health: "ok" | "degraded" | "down" | "unknown";
  /** Application UI serving layer state — a terminal cannot trade without it. */
  uiStatus: "ok" | "down" | "unknown";
  uiVersion: string | null;
  ready: boolean;
}

export interface DiagnosticBundle {
  generatedAt: string;
  system: SystemInformation;
  services: { id: string; status: string; detail?: string }[];
  configuration: Record<string, unknown>;
  logs: { source: string; lines: string[] }[];
  notice: string;
}

export function buildDiagnosticBundle(input: {
  generatedAt?: string;
  system: Partial<SystemInformation>;
  services?: { id: string; status: string; detail?: string }[];
  configuration?: Record<string, unknown>;
  logs?: { source: string; lines: string[] }[];
}): DiagnosticBundle {
  const system: SystemInformation = {
    product: NOVA_PRODUCT,
    appVersion: APP_VERSION,
    requiredSchemaVersion: REQUIRED_SCHEMA_VERSION,
    schemaVersion: null,
    runtime: "local",
    installId: null,
    postgresVersion: null,
    migrationsApplied: null,
    lastBackupAt: null,
    lastBackupStatus: "none",
    health: "unknown",
    uiStatus: "unknown",
    uiVersion: null,
    ready: false,
    ...input.system,
  };

  return {
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    system,
    services: input.services ?? [],
    configuration: redactRecord(input.configuration ?? {}),
    logs: (input.logs ?? []).map((l) => ({ source: l.source, lines: l.lines.map(redactText) })),
    notice:
      "Generated by NOVA Hospitality for Nolmark support. Secrets, credentials and keys are removed before writing.",
  };
}

/** Roles allowed to see system information / generate diagnostics. */
export const DIAGNOSTIC_ROLES = ["owner", "admin"] as const;

export function canRunDiagnostics(role: string | null | undefined): boolean {
  return (DIAGNOSTIC_ROLES as readonly string[]).includes(String(role ?? "").toLowerCase());
}

/** Restore is destructive: only an owner may perform it. */
export function canRestoreBackup(role: string | null | undefined): boolean {
  return String(role ?? "").toLowerCase() === "owner";
}
