/**
 * The one dataset model every exporter reads. A workbook is described once and
 * then rendered to CSV, XLSX or JSON — so the columns, order and values are
 * identical regardless of the format the user picked.
 *
 * Raw data sheets stay clean: no merged cells, no title rows, no blank
 * spacers. Metadata lives on its own sheet (§22).
 */
import { machineValue } from "../core/format";
import type { CellValue, DocumentColumn } from "../core/types";

export interface ExportSheet {
  name: string;
  columns: DocumentColumn[];
  rows: Record<string, CellValue>[];
}

export interface ExportMetadata {
  generatedAt: string;
  generatedBy?: string | null;
  tenant?: string | null;
  property?: string | null;
  outlet?: string | null;
  dateRange?: string | null;
  filters?: Record<string, string | number | boolean | null | undefined>;
  source?: string | null;
  rowCount?: number;
}

export interface ExportWorkbook {
  /** Document type id this export belongs to. */
  type: string;
  title: string;
  fileStem: string;
  metadata: ExportMetadata;
  sheets: ExportSheet[];
}

/** Sheet names are limited to 31 chars by the XLSX format. */
export function safeSheetName(name: string): string {
  return name.replace(/[\\/?*[\]:]/g, " ").slice(0, 31) || "Sheet";
}

/** Header row + machine-readable value matrix for one sheet. */
export function sheetMatrix(sheet: ExportSheet): (string | number | boolean | null)[][] {
  const header = sheet.columns.map((c) => c.label);
  const body = sheet.rows.map((row) => sheet.columns.map((c) => machineValue(row[c.key] ?? null, c.format)));
  return [header, ...body];
}

/** Flat key/value matrix for the metadata sheet. */
export function metadataMatrix(meta: ExportMetadata): (string | number | boolean | null)[][] {
  const rows: (string | number | boolean | null)[][] = [
    ["Field", "Value"],
    ["Generated At", meta.generatedAt],
    ["Generated By", meta.generatedBy ?? ""],
    ["Tenant", meta.tenant ?? ""],
    ["Property", meta.property ?? ""],
    ["Outlet", meta.outlet ?? ""],
    ["Date Range", meta.dateRange ?? ""],
    ["Source", meta.source ?? ""],
    ["Row Count", meta.rowCount ?? ""],
  ];
  for (const [key, value] of Object.entries(meta.filters ?? {})) {
    if (value === undefined || value === null || value === "") continue;
    rows.push([`Filter: ${key}`, String(value)]);
  }
  return rows;
}

export function totalRows(workbook: ExportWorkbook): number {
  return workbook.sheets.reduce((sum, s) => sum + s.rows.length, 0);
}