import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { ArrowLeft, Loader2, Mail } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { PRODUCT } from "@/config/product";
import { presentUserFacingError } from "@/lib/errors/present-error";

export const Route=createFileRoute("/auth_/forgot-password")({head:()=>({meta:[{title:"Reset password — "+PRODUCT.shortName},{name:"robots",content:"noindex,nofollow"}]}),component:ForgotPasswordPage});
function ForgotPasswordPage(){
 const [email,setEmail]=useState(""); const [loading,setLoading]=useState(false); const [sent,setSent]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/auth/reset-password`});setLoading(false);if(error){toast.error(presentUserFacingError(error,"We couldn't start the password reset.").message);return;}setSent(true);};
 return <main className="min-h-screen bg-[#f7f8f5] text-[#172019]"><div className="mx-auto flex min-h-screen max-w-[560px] items-center justify-center px-5 py-10 sm:px-8"><div className="w-full"><img src="/brand/lexibite-wordmark.svg" alt="LexiBite" className="h-10 w-auto max-w-[11rem]"/><p className="mt-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#55705a]">{PRODUCT.tagline}</p><div className="mb-8 mt-10"><p className="text-sm font-medium text-[#55705a]">Account recovery</p><h1 className="mt-2 text-3xl font-semibold">Reset your password</h1><p className="mt-2 text-sm leading-6 text-[#667069]">Enter your account email and we’ll send instructions to create a new password.</p></div>{sent?<div className="rounded-2xl border border-[#dfe4df] bg-white p-8 shadow-[0_18px_50px_rgba(23,61,34,0.08)]"><Mail className="size-6 text-[#2f7139]"/><h2 className="mt-5 text-xl font-semibold">Check your email</h2><p className="mt-2 text-sm leading-6 text-[#667069]">If an account is associated with that address, a password-reset link has been sent.</p><Link to="/auth" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#2f7139] hover:underline"><ArrowLeft className="size-4"/>Back to sign in</Link></div>:<form onSubmit={submit} className="rounded-2xl border border-[#dfe4df] bg-white p-8 shadow-[0_18px_50px_rgba(23,61,34,0.08)]"><label className="block"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-[#59645d]">Email address</span><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@restaurant.com" className="mt-2 h-12 w-full rounded-lg border border-[#d5dbd6] px-4 text-sm outline-none focus:border-[#2f7139] focus:ring-4 focus:ring-[#2f7139]/10"/></label><button disabled={loading} className="mt-6 inline-flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#2f7139] text-sm font-semibold text-white disabled:opacity-60">{loading?<Loader2 className="size-4 animate-spin"/>:<Mail className="size-4"/>}{loading?"Sending…":"Send reset link"}</button><Link to="/auth" className="mt-5 inline-flex w-full items-center justify-center gap-2 text-sm font-semibold text-[#55705a] hover:text-[#2f7139] hover:underline"><ArrowLeft className="size-4"/>Back to sign in</Link></form>}</div></div></main>;
}