/**
 * Canonical Restaurant & Bar OS events.
 *
 * These are the *only* thing the Intelligence Core consumes from this module.
 * The envelope follows the existing intelligence event standard and adds the
 * commercial dimensions (tenant / property / location) every hospitality group
 * needs for segmentation.
 */
import { z } from "zod";

export const RESTAURANT_EVENT_TYPES = [
  "restaurant.menu.created",
  "restaurant.menu.updated",
  "restaurant.menu.published",
  "restaurant.item.sold",
  "restaurant.order.opened",
  "restaurant.order.item.added",
  "restaurant.order.item.voided",
  "restaurant.order.transferred",
  "restaurant.order.reopened",
  "restaurant.order.cancelled",
  "restaurant.receipt.issued",
  "restaurant.receipt.delivered",
  "restaurant.receipt.delivery.requested",
  "restaurant.receipt.delivery.sent",
  "restaurant.receipt.delivery.failed",
  "restaurant.receipt.delivery.delivered",
  "restaurant.bill.requested",
  "restaurant.bill.presented",
  "restaurant.table.released",
  "restaurant.order.closed",
  "restaurant.order.voided",
  "restaurant.payment.captured",
  "restaurant.payment.refunded",
  "restaurant.payment.room_charge_posted",
  "restaurant.payment.room_charge_failed",
  "restaurant.payment.room_charge_unknown",
  "restaurant.kitchen.ticket.fired",
  "restaurant.kitchen.ticket.ready",
  "restaurant.kitchen.ticket.delayed",
  "restaurant.stock.moved",
  "restaurant.stock.transferred",
  "restaurant.profitability.computed",
  "restaurant.inventory.low",
  "restaurant.inventory.adjusted",
  "restaurant.inventory.location.created",
  "restaurant.inventory.transfer.requested",
  "restaurant.inventory.transfer.approved",
  "restaurant.inventory.transfer.rejected",
  "restaurant.inventory.transfer.dispatched",
  "restaurant.inventory.transfer.received",
  "restaurant.inventory.adjustment.created",
  "restaurant.inventory.waste.recorded",
  "restaurant.inventory.stocktake.started",
  "restaurant.inventory.stocktake.completed",
  "restaurant.inventory.variance.detected",
  "restaurant.inventory.reservation.created",
  "restaurant.inventory.reservation.released",
  "restaurant.inventory.movement.reversed",
  "restaurant.inventory.batch.created",
  "restaurant.inventory.batch.expiring",
  "restaurant.inventory.batch.expired",
  "restaurant.purchase.created",
  "restaurant.purchase.requested",
  "restaurant.purchase.request.approved",
  "restaurant.purchase.request.rejected",
  "restaurant.purchase.order.created",
  "restaurant.purchase.order.confirmed",
  "restaurant.purchase.order.submitted",
  "restaurant.purchase.order.approved",
  "restaurant.purchase.order.cancelled",
  "restaurant.purchase.received",
  "restaurant.purchase.variance.detected",
  "restaurant.purchase.invoice.recorded",
  "restaurant.purchase.invoice.matched",
  "restaurant.recipe.updated",
  "restaurant.recipe.created",
  "restaurant.recipe.versioned",
  "restaurant.product.created",
  "restaurant.product.updated",
  "restaurant.modifier.created",
  "restaurant.production.started",
  "restaurant.production.completed",
  "restaurant.production.variance.detected",
  "restaurant.cost.changed",
  "restaurant.price.created",
  "restaurant.price.updated",
  "restaurant.price_list.created",
  "restaurant.price_list.updated",
  "restaurant.rounding_rule.changed",
  "restaurant.price.approved",
  "restaurant.tax.rule.created",
  "restaurant.discount.applied",
  "restaurant.promotion.started",
  "restaurant.promotion.ended",
  "restaurant.waste.recorded",
  "restaurant.shift.closed",
  "restaurant.daily.revenue.closed",
  "restaurant.supplier.updated",
  "restaurant.requisition.created",
  "restaurant.requisition.submitted",
  "restaurant.requisition.approved",
  "restaurant.requisition.rejected",
  "restaurant.requisition.issued",
  "restaurant.requisition.fulfilled",
  /* --- Bar & beverage facts (Sprint 5.6). Same module, same envelope. --- */
  "bar.stock.low",
  "bar.stocktake.completed",
  "bar.waste.recorded",
  "bar.requisition.created",
  "bar.requisition.fulfilled",
  "bar.transfer.completed",
  "bar.ticket.delayed",
  "bar.beverage.variance.detected",
  "bar.product.performance.changed",
  "bar.pour.configured",
  "bar.drink.comped",
  /* --- Menu lifecycle, guest context & menu intelligence (Sprint 5.11). --- */
  "restaurant.menu.item.updated",
  "restaurant.menu.item.activated",
  "restaurant.menu.item.paused",
  "restaurant.menu.item.discontinued",
  "restaurant.menu.item.archived",
  "restaurant.menu.item.deleted",
  "restaurant.guest.preference.observed",
  "restaurant.guest.preference.confirmed",
  "restaurant.guest.allergen.recorded",
  "restaurant.guest.dietary_requirement.recorded",
  "restaurant.menu.opportunity.detected",
  "restaurant.menu.recommendation.generated",
  "restaurant.menu.recommendation.accepted",
  "restaurant.menu.recommendation.dismissed",
  /* --- Reconciliation & financial control (Sprint 5.12). --- */
  "restaurant.day.close.opened",
  "restaurant.day.tender.declared",
  "restaurant.reconciliation.run.completed",
  "restaurant.reconciliation.exception.detected",
  "restaurant.reconciliation.exception.resolved",
  "restaurant.day.closed",
  "restaurant.day.reopened",
] as const;
export type RestaurantEventType = (typeof RESTAURANT_EVENT_TYPES)[number];

/** Severity mirrors the intelligence severity scale. */
export const RESTAURANT_EVENT_SEVERITY: Record<RestaurantEventType, "info" | "low" | "medium" | "high"> = {
  "restaurant.menu.created": "info",
  "restaurant.menu.updated": "info",
  "restaurant.menu.published": "low",
  "restaurant.item.sold": "info",
  "restaurant.order.opened": "info",
  "restaurant.order.item.added": "info",
  "restaurant.order.item.voided": "medium",
  "restaurant.order.transferred": "low",
  "restaurant.order.reopened": "high",
  "restaurant.order.cancelled": "high",
  "restaurant.receipt.issued": "info",
  "restaurant.receipt.delivered": "info",
  "restaurant.receipt.delivery.requested": "info",
  "restaurant.receipt.delivery.sent": "info",
  "restaurant.receipt.delivery.failed": "medium",
  "restaurant.receipt.delivery.delivered": "info",
  "restaurant.bill.requested": "info",
  "restaurant.bill.presented": "info",
  "restaurant.table.released": "info",
  "restaurant.order.closed": "low",
  "restaurant.order.voided": "medium",
  "restaurant.payment.captured": "info",
  "restaurant.payment.refunded": "high",
  "restaurant.payment.room_charge_posted": "info",
  "restaurant.payment.room_charge_failed": "high",
  "restaurant.payment.room_charge_unknown": "high",
  "restaurant.kitchen.ticket.fired": "info",
  "restaurant.kitchen.ticket.ready": "info",
  "restaurant.kitchen.ticket.delayed": "high",
  "restaurant.stock.moved": "info",
  "restaurant.stock.transferred": "low",
  "restaurant.profitability.computed": "medium",
  "restaurant.inventory.low": "high",
  "restaurant.inventory.adjusted": "low",
  "restaurant.inventory.location.created": "info",
  "restaurant.inventory.transfer.requested": "low",
  "restaurant.inventory.transfer.approved": "low",
  "restaurant.inventory.transfer.rejected": "medium",
  "restaurant.inventory.transfer.dispatched": "low",
  "restaurant.inventory.transfer.received": "low",
  "restaurant.inventory.adjustment.created": "medium",
  "restaurant.inventory.waste.recorded": "medium",
  "restaurant.inventory.stocktake.started": "info",
  "restaurant.inventory.stocktake.completed": "medium",
  "restaurant.inventory.variance.detected": "high",
  "restaurant.inventory.reservation.created": "info",
  "restaurant.inventory.reservation.released": "info",
  "restaurant.inventory.movement.reversed": "medium",
  "restaurant.inventory.batch.created": "info",
  "restaurant.inventory.batch.expiring": "medium",
  "restaurant.inventory.batch.expired": "high",
  "restaurant.purchase.created": "low",
  "restaurant.purchase.requested": "low",
  "restaurant.purchase.request.approved": "low",
  "restaurant.purchase.request.rejected": "medium",
  "restaurant.purchase.order.created": "low",
  "restaurant.purchase.order.confirmed": "low",
  "restaurant.purchase.order.submitted": "low",
  "restaurant.purchase.order.approved": "low",
  "restaurant.purchase.order.cancelled": "medium",
  "restaurant.purchase.received": "low",
  "restaurant.purchase.variance.detected": "high",
  "restaurant.purchase.invoice.recorded": "info",
  "restaurant.purchase.invoice.matched": "low",
  "restaurant.recipe.updated": "low",
  "restaurant.recipe.created": "info",
  "restaurant.recipe.versioned": "low",
  "restaurant.product.created": "info",
  "restaurant.product.updated": "info",
  "restaurant.modifier.created": "info",
  "restaurant.production.started": "info",
  "restaurant.production.completed": "low",
  "restaurant.production.variance.detected": "high",
  "restaurant.cost.changed": "medium",
  "restaurant.price.created": "low",
  "restaurant.price.updated": "medium",
  "restaurant.price_list.created": "low",
  "restaurant.price_list.updated": "medium",
  "restaurant.rounding_rule.changed": "medium",
  "restaurant.price.approved": "low",
  "restaurant.tax.rule.created": "medium",
  "restaurant.discount.applied": "low",
  "restaurant.promotion.started": "low",
  "restaurant.promotion.ended": "info",
  "restaurant.waste.recorded": "medium",
  "restaurant.shift.closed": "info",
  "restaurant.daily.revenue.closed": "low",
  "restaurant.supplier.updated": "info",
  "restaurant.requisition.created": "info",
  "restaurant.requisition.submitted": "low",
  "restaurant.requisition.approved": "low",
  "restaurant.requisition.rejected": "medium",
  "restaurant.requisition.issued": "low",
  "restaurant.requisition.fulfilled": "low",
  "bar.stock.low": "high",
  "bar.stocktake.completed": "medium",
  "bar.waste.recorded": "medium",
  "bar.requisition.created": "info",
  "bar.requisition.fulfilled": "low",
  "bar.transfer.completed": "low",
  "bar.ticket.delayed": "high",
  "bar.beverage.variance.detected": "high",
  "bar.product.performance.changed": "medium",
  "bar.pour.configured": "info",
  "bar.drink.comped": "medium",
  "restaurant.menu.item.updated": "info",
  "restaurant.menu.item.activated": "low",
  "restaurant.menu.item.paused": "low",
  "restaurant.menu.item.discontinued": "medium",
  "restaurant.menu.item.archived": "low",
  "restaurant.menu.item.deleted": "medium",
  "restaurant.guest.preference.observed": "info",
  "restaurant.guest.preference.confirmed": "low",
  "restaurant.guest.allergen.recorded": "high",
  "restaurant.guest.dietary_requirement.recorded": "medium",
  "restaurant.menu.opportunity.detected": "low",
  "restaurant.menu.recommendation.generated": "low",
  "restaurant.menu.recommendation.accepted": "low",
  "restaurant.menu.recommendation.dismissed": "info",
  "restaurant.day.close.opened": "info",
  "restaurant.day.tender.declared": "low",
  "restaurant.reconciliation.run.completed": "low",
  "restaurant.reconciliation.exception.detected": "high",
  "restaurant.reconciliation.exception.resolved": "low",
  "restaurant.day.closed": "low",
  // Reopening a closed day rewrites financial evidence after the fact.
  "restaurant.day.reopened": "high",
};

export const restaurantEventSchema = z.object({
  type: z.enum(RESTAURANT_EVENT_TYPES),
  tenantId: z.string().uuid(),
  propertyId: z.string().uuid().optional(),
  locationId: z.string().uuid().optional(),
  entityType: z.string().max(60).optional(),
  entityId: z.string().uuid().optional(),
  /** Free-form, event-specific body. Keep it flat and numeric where possible. */
  payload: z.record(z.string(), z.unknown()).default({}),
  source: z.string().max(60).default("restaurant-os"),
  occurredAt: z.string().datetime().optional(),
  correlationId: z.string().uuid().optional(),
  /** Idempotency. Derived when omitted. */
  dedupeKey: z.string().max(200).optional(),
});
export type RestaurantEventInput = z.infer<typeof restaurantEventSchema>;

/** Stable idempotency key: same fact never lands twice. */
export function restaurantDedupeKey(e: RestaurantEventInput): string {
  return (
    e.dedupeKey ??
    [
      e.type,
      e.tenantId,
      e.locationId ?? e.propertyId ?? "tenant",
      e.entityId ?? "none",
      e.occurredAt ?? new Date().toISOString().slice(0, 13),
    ].join(":")
  );
}